name: OpenStatus Monitor 游니

on:
  # 1. Ejecutar autom치ticamente cada 10 minutos
  schedule:
    - cron: '*/10 * * * *'
  # 2. Permitir que t칰 lo ejecutes manualmente desde la pesta침a "Actions" (칰til para probar)
  workflow_dispatch:

jobs:
  check-sites:
    runs-on: ubuntu-latest # Usamos una m치quina virtual Linux est치ndar
    timeout-minutes: 3 #si tarda m치s de 3 minutos, se cancela el job

    steps:
      - name: 游닌 Descargar tu c칩digo (Checkout)
        uses: actions/checkout@v4

      - name: 游릭 Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 游닍 Instalar dependencias
        # Entramos a la carpeta 'scripts' porque ah칤 est치 tu package.json
        run: |
          cd scripts
          npm install

      - name: 游 Ejecutar script de monitoreo
        # Aqu칤 inyectamos las llaves secretas para que el script pueda usarlas
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          cd scripts
          node ping.js